# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20170711_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('T', 'Topic'), ('P', 'Personal')], default='T', max_length=1),
        ),
    ]
