# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('P', 'Personal'), ('T', 'Topic')], default='T', max_length=1),
        ),
    ]
