# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20170807_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('T', 'Topic'), ('P', 'Personal')], default='T', max_length=1),
        ),
    ]
