# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20171128_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('P', 'Personal'), ('T', 'Topic')], default='T', max_length=1),
        ),
    ]
